---
title: "HW 2"
author: "STAT - S782"
date: "Due 24 October 2017"
output:
  pdf_document:
    includes:
      in_header: ../Support/782macros.tex
    number_sections: yes
    template: ../Support/dm-docs.tex
    toc: no
---

\renewcommand{\P}[1]{\mathbb{P}\left(#1\right)}

# Bin packing.

Bin packing. This is a classical application of McDiarmid’s inequality. Let $X_1,\ldots,X_n$ be i.i.d. random variables taking values in $[0,1]$. Each $X_i$ is the size of a package to be shipped. The packages are shipped in bins of size 1, so each bin can hold any set of packages whose sizes sum to at most 1. Let $B_n = f (X_1,\ldots,X_n)$ be the minimal number of bins needed to ship the packages with sizes $X_1,\ldots,X_n$. Computing $B_n$ is a hard combinatorial optimization problem; however, we can say something about its mean and tail behavior.

##

Let $\mu$ be the common mean of the $X_i$'s. Show that $\Expect{B_n} \geq n\mu$.

##

Prove that for any $\epsilon >0$,
\[
\P{n^{-1} B_n \leq \mu - \epsilon} \leq \exp\left(-2n\epsilon^2\right).
\]

# Orthogonal design lasso bits

Let $y_i = x_i^\top \beta^* + \eta_i$ for $i=1,\ldots,n$. Assume that the design matrix $\X = (x_1, \ldots, x_n)^\top$ and that $\X^\top\X=nI_p$. Also assume that $\log\Expect{e^{\lambda\eta_i}} \leq \sigma^2\lambda^2/2$. Suppose that $\beta^*$ is sparse: $\mathcal{S}=\{j : \beta^*_j\neq 0\}$ and that $\beta^*$ is such that $\norm{\beta^*_{S^c}}_1 \leq L\norm{\beta^*_S}$ for some $L$. Let
\[
\hat\beta = \argmin_\beta \frac{1}{2n} \norm{Y-\X\beta} + \lambda\norm{\beta}_1.
\]

## 

Derive the so-called "basic inequality":
\[
\norm{\X\beta^*-\X\hat\beta} + \lambda\norm{\beta}_1 \leq \frac{1}{n}\eta^\top \X(\beta^*-\hat\beta)+\lambda\norm{\beta_*}_1
\]

## 

Let $X_j$ be the $j^{th}$ column of $\X$. Find a constant $M$ such that $\P{\mathcal{G}} \geq 1-2e^{-\delta}$ for 
\[
\mathcal{G} = \left\{\max_{j} |\eta^\top X_j| < M\right\}.
\]



# Empirical Rademacher Complexity

Prove the following result. Let $H$ be a set of hypotheses bounded by $M>0$ and consider an i.i.d. sample of size $n$. For any $h\in H$, with probability at least $1-\delta$
\[
R_n(h) \leq \hat{R}_n(h) + \hat{\mathcal{R}}_n(H) + 3M\sqrt{\frac{2\log(2/\delta)}{2}}.
\]
